[package]
name = "compatibility-suite"
version = "0.0.0"
edition = "2024"

[dev-dependencies]
anyhow = "1.0.75"
async-trait = "0.1.74"
base64 = "0.22.0"
bytes = "1.5.0"
cucumber = "0.21.1"
futures = "0.3.29"
itertools = "0.14.0"
lazy_static = "1.4.0"
maplit = "1.0.2"
pact_models = { version = "~1.3.6" }
pact_matching = { version = "~2.0.1" }
pact_mock_server = { version = "~2.1.3" }
pact_verifier = { version = "~1.3.2" }
pact_consumer = { version = "~1.4.1" }
pretty_assertions = "1.4.0"
regex = "1.10.2"
reqwest = { version = "0.12.3", default-features = false, features = ["rustls-tls-native-roots", "json"] }
rocket = { version = "0.5.0", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.108"
sxd-document = "0.3.2"
tokio = { version = "1.33.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "tracing-log", "fmt"] }
uuid = { version = "1.5.0", features = ["v4"] }

[[test]]
name = "v1_consumer"
harness = false

[[test]]
name = "v1_provider"
harness = false

[[test]]
name = "v2_consumer"
harness = false

[[test]]
name = "v2_provider"
harness = false

[[test]]
name = "v3"
harness = false

[[test]]
name = "v3_provider"
harness = false

[[test]]
name = "v3_message"
harness = false

[[test]]
name = "v4"
harness = false
