BUILD_CLI_TEST_TASK_TEMPLATE: &BUILD_CLI_TEST_TASK_TEMPLATE
  test_pact_mock_server_cli_script: |
    cd rust/pact_mock_server_cli
    ./build-cross.sh
    ../target/${BUILD_TARGET}/release/pact_mock_server_cli --help
    rm -rf ../target/
  test_pact_verifier_cli_script: |
    cd rust/pact_verifier_cli
    ./build-cross.sh
    ../target/${BUILD_TARGET}/release/pact_verifier_cli --help

BUILD_FFI_TASK_TEMPLATE: &BUILD_FFI_TASK_TEMPLATE
  build_ffi_script: |
    cd rust/pact_ffi
    ./build-cross.sh

cli_linux_arm64_task: 
  arm_container:
    image: rustlang/rust:nightly
    cpu: 4
    memory: 12G
  env:
    CIRRUS_CI: true
    matrix:
      - target: aarch64-unknown-linux-gnu
  << : *BUILD_CLI_TEST_TASK_TEMPLATE

ffi_linux_arm64_task: 
  arm_container:
    image: rustlang/rust:nightly
    cpu: 4
    memory: 12G
  env:
    CIRRUS_CI: true
    matrix:
      - target: aarch64-unknown-linux-gnu
  << : *BUILD_FFI_TASK_TEMPLATE

cli_macos_arm64_task: 
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  setup_script: brew install rust
  env:
    BUILD_TARGET: aarch64-apple-darwin 
  << : *BUILD_CLI_TEST_TASK_TEMPLATE

ffi_macos_arm64_task: 
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  setup_script: brew install rust
  env:
    BUILD_TARGET: aarch64-apple-darwin 
  << : *BUILD_FFI_TASK_TEMPLATE



