FROM alpine

RUN apk add cargo musl-dev gcc git

WORKDIR /home

RUN git clone --depth 1 --branch feat/purego https://github.com/YOU54F/pact-reference.git

WORKDIR /home/pact-reference/rust/pact_ffi

RUN cargo build

WORKDIR /home/pact-reference/go

RUN apk add go gdb

RUN mkdir -p /root/.config/gdb
RUN echo "set auto-load safe-path /" >> /root/.config/gdb/gdbinit

RUN go test -v pact/go/native/native -count 1 -c

CMD ["sh", "-c", "PACT_PROVIDER_DIR=./native/pacts_http gdb -ex run --args ./native.test -test.count=5"]