[workspace]
members = [
    "pact_models",
    "pact_matching",
    "pact_mock_server",
    "pact_mock_server_cli",
    "pact_consumer",
    "pact_verifier",
    "pact_verifier_cli",
    "pact_cli",
    "pact_ffi"
]
exclude = [
    "pact_wasm"
]

[profile.release]
# https://github.com/johnthagen/min-sized-rust
# libpactffi.dylib size 24M -> 9.4M
# pact_verifier_cli size 19M -> 6.4M
# pact_mock_server_cli size 19M -> 5.6M

## Original Sizes

# du -sh ../target/release/
#  24M    ../target/release/libpact_ffi.dylib
#  19M    ../target/release/pact_verifier_cli
#  18M    ../target/release/pact_mock_server_cli

## Smallest compress to date.
## using strip=true, opt-level=z, codegen-units=1, panic=abort, lto=true
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
codegen-units = 1
panic = "abort"
lto = true
# 9.4M    ../target/release/libpact_ffi.dylib
# 6.4M    ../target/release/pact_verifier_cli
# 5.6M    ../target/release/pact_mock_server_cli



# strip = true  # Automatically strip symbols from the binary.
#  19M    ../target/release/libpact_ffi.dylib
#  15M    ../target/release/pact_verifier_cli
#  14M    ../target/release/pact_mock_server_cli
# opt-level = "z"  # Optimize for size.
#  21M    ../target/release/libpact_ffi.dylib
#  18M    ../target/release/pact_verifier_cli
#  16M    ../target/release/pact_mock_server_cli
# lto = true 
#  24M    ../target/release/libpact_ffi.dylib
#  15M    ../target/release/pact_verifier_cli
#  12M    ../target/release/pact_mock_server_cli
# codegen-units = 1
#  18M    ../target/release/libpact_ffi.dylib
#  15M    ../target/release/pact_verifier_cli
#  14M    ../target/release/pact_mock_server_cli
# panic = "abort"
#  17M    ../target/release/libpact_ffi.dylib
#  14M    ../target/release/pact_verifier_cli
#  13M    ../target/release/pact_mock_server_cli

## using strip=true, opt-level=z, codegen-units=1
# strip = true  # Automatically strip symbols from the binary.
# opt-level = "z"  # Optimize for size. # saves 4mb
# codegen-units = 1 # saves 6mb
#  11M    ../target/release/libpact_ffi.dylib
# 9.9M    ../target/release/pact_verifier_cli
# 9.1M    ../target/release/pact_mock_server_cli

## using strip=true, opt-level=z, codegen-units=1, panic=abort
# strip = true  # Automatically strip symbols from the binary.
# opt-level = "z"  # Optimize for size.
# codegen-units = 1
# panic = "abort"
# 9.4M    ../target/release/libpact_ffi.dylib
# 8.7M    ../target/release/pact_verifier_cli
# 8.0M    ../target/release/pact_mock_server_cli



[patch.crates-io]
onig = { git = "https://github.com/rust-onig/rust-onig", default-features = false }
