[workspace]
members = [
    "pact_*"
]
exclude = [
    "pact_mock_server",
    "pact_mock_server_cli",
    "pact_wasm",
    "pact_cli"
]
resolver = "2"

[patch.crates-io]
onig = { git = "https://github.com/rust-onig/rust-onig", default-features = false }

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1