[workspace]
members = [
    "pact_*"
]
exclude = [
    "pact_wasm"
]
resolver = "2"

[patch.crates-io]
onig = { git = "https://github.com/rust-onig/rust-onig", default-features = false }
pact_models = { path = "pact_models" }

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
codegen-units = 1
panic = "abort"
lto = true
# https://github.com/johnthagen/min-sized-rust

# Original Sizes
#  24M    libpact_ffi.dylib
#  19M    pact_verifier_cli
#  18M    pact_mock_server_cli

# libpactffi.dylib size 24M -> 9.4M
# pact_verifier_cli size 19M -> 6.4M
# pact_mock_server_cli size 19M -> 5.6M