name: test alpine cli

on:
  push:
    paths:
      - '!.cirrus.yml'
      - 'rust/**'
      - '.github/workflows/alpine_cli.yml'
  pull_request:
    paths:
      - '!.cirrus.yml'
      - 'rust/**'
      - '.github/workflows/alpine_cli.yml'

jobs:
  cross:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        crate: ["pact_verifier_cli","pact_mock_server_cli"]
    steps:
      - uses: actions/checkout@v3
      - run: docker run --privileged --rm tonistiigi/binfmt --install all
      - name: Testing alpine releases for ${{ matrix.crate }}
        run: ./test-alpine-multi.sh
        working-directory: rust
        env:
          LOAD: true
      - name: Building alpine releases for ${{ matrix.crate }}
        run: ./test-alpine-multi.sh
        working-directory: rust
        env:
          BUILD_MULTI: true