name: test alpine cli

on:
  push:
    paths:
      - '!.cirrus.yml'
      - 'rust/**'
      - '.github/alpine_cli.yml'
  pull_request:
    paths:
      - '!.cirrus.yml'
      - 'rust/**'
      - '.github/alpine_cli.yml'

jobs:
  cross:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        crate: ["pact_verifier_cli","pact_mock_server_cli"]
    steps:
      - uses: actions/checkout@v3
      - name: Testing alpine releases for ${{ matrix.crate }}
        run: ./test-alpine-multi.sh
        working-directory: rust