name: Pact-Rust Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
#  cancel-in-progress: false

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-13, macos-14 ]
        rust: [ stable ]
    env:
      pact_do_not_track: true
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: Install shared mime info DB
        if: runner.os == 'macOS'
        run: brew install shared-mime-info
      - name: Tests
        run: cargo nextest run
        working-directory: rust
        env:
          RUST_LOG: debug
          RUST_BACKTRACE: 1
      - name: Run mock_server_logs test
        run: cargo nextest run -p pact_ffi returns_mock_server_logs -- --include-ignored
        working-directory: rust
        env:
          RUST_LOG: debug
          RUST_BACKTRACE: 1
      - name: Clippy
        if: runner.os == 'Linux'
        run: cargo clippy
        working-directory: rust

  musl-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
         docker run --rm --user "$(id -u)":"$(id -g)" -v $(pwd):/workspace -w /workspace/rust -t -e TZ=UTC pactfoundation/rust-musl-build ./scripts/ci-musl-build.sh


  check-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo check --no-default-features
        working-directory: rust
