name: Pact-Rust Compatibility Suite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: "1"
  RUST_LOG: "debug"
  PACT_DO_NOT_TRACK: "true"
  CARGO_TERM_COLOR: always

jobs:
  compatibility-suite:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: Run Cucumber
        # Note: cucumber's test executables are incompatible with nextest
        # See: https://github.com/nextest-rs/nextest/issues/1329
        run: cargo test
        working-directory: compatibility-suite
