name: Pact-Rust FFI Build

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        rust: [ stable ]
        target: # https://doc.rust-lang.org/nightly/rustc/platform-support.html
            # Tier 1
            - aarch64-unknown-linux-gnu
            - i686-pc-windows-gnu
            - i686-pc-windows-msvc
            - i686-unknown-linux-gnu
            - x86_64-apple-darwin
            - x86_64-pc-windows-gnu
            - x86_64-pc-windows-msvc
            - x86_64-unknown-linux-gnu
            - # Tier 2 with host tools
            - aarch64-apple-darwin
            - aarch64-pc-windows-msvc
            - aarch64-unknown-linux-musl
            - arm-unknown-linux-gnueabi
            - arm-unknown-linux-gnueabihf
            - armv7-unknown-linux-gnueabihf
            - mips-unknown-linux-gnu
            - mips64-unknown-linux-gnuabi64
            - mips64el-unknown-linux-gnuabi64
            - mipsel-unknown-linux-gnu
            - powerpc-unknown-linux-gnu
            - powerpc64-unknown-linux-gnu
            - powerpc64le-unknown-linux-gnu
            - riscv64gc-unknown-linux-gnu
            - s390x-unknown-linux-gnu
            - x86_64-unknown-freebsd
            - x86_64-unknown-illumos
            - x86_64-unknown-linux-musl
            - x86_64-unknown-netbsd
            # Tier 2
            - aarch64-apple-ios
            - aarch64-apple-ios-sim
            - aarch64-fuchsia
            - aarch64-unknown-fuchsia
            - aarch64-linux-android
            - aarch64-unknown-none-softfloat
            - aarch64-unknown-none
            - aarch64-unknown-uefi
            - arm-linux-androideabi
            - arm-unknown-linux-musleabi
            - arm-unknown-linux-musleabihf
            - armebv7r-none-eabi
            - armebv7r-none-eabihf
            - armv5te-unknown-linux-gnueabi
            - armv5te-unknown-linux-musleabi
            - armv7-linux-androideabi
            - armv7-unknown-linux-gnueabi
            - armv7-unknown-linux-musleabi
            - armv7-unknown-linux-musleabihf
            - armv7a-none-eabi
            - armv7r-none-eabi
            - armv7r-none-eabihf
            - asmjs-unknown-emscripten
            - i586-pc-windows-msvc
            - i586-unknown-linux-gnu
            - i586-unknown-linux-musl
            - i686-linux-android
            - i686-unknown-freebsd
            - i686-unknown-linux-musl
            - i686-unknown-uefi
            - mips-unknown-linux-musl
            - mips64-unknown-linux-muslabi64
            - mips64el-unknown-linux-muslabi64
            - mipsel-unknown-linux-musl
            - nvptx64-nvidia-cuda
            - riscv32i-unknown-none-elf
            - riscv32imac-unknown-none-elf
            - riscv32imc-unknown-none-elf
            - riscv64gc-unknown-none-elf
            - riscv64imac-unknown-none-elf
            - sparc64-unknown-linux-gnu
            - sparcv9-sun-solaris
            - thumbv6m-none-eabi
            - thumbv7em-none-eabi
            - thumbv7em-none-eabihf
            - thumbv7m-none-eabi
            - thumbv7neon-linux-androideabi
            - thumbv7neon-unknown-linux-gnueabihf
            - thumbv8m.base-none-eabi
            - thumbv8m.main-none-eabi
            - thumbv8m.main-none-eabihf
            - wasm32-unknown-emscripten
            - wasm32-unknown-unknown
            - wasm32-wasi
            - x86_64-apple-ios
            - x86_64-fortanix-unknown-sgx
            - x86_64-fuchsia
            - x86_64-unknown-fuchsia
            - x86_64-linux-android
            - x86_64-pc-solaris
            - x86_64-unknown-linux-gnux32
            - x86_64-unknown-none
            - x86_64-unknown-redox
            - x86_64-unknown-uefi
            # Tier 3
            - aarch64-apple-ios-macabi
            - aarch64-apple-tvos
            - aarch64-apple-watchos-sim
            - aarch64-kmc-solid_asp3
            - aarch64-nintendo-switch-freestanding
            - aarch64-pc-windows-gnullvm
            - aarch64-unknown-linux-ohos
            - aarch64-unknown-nto-qnx710
            - aarch64-unknown-freebsd
            - aarch64-unknown-hermit
            - aarch64-unknown-linux-gnu_ilp32
            - aarch64-unknown-netbsd
            - aarch64-unknown-openbsd
            - aarch64-unknown-redox
            - aarch64-uwp-windows-msvc
            - aarch64-wrs-vxworks
            - aarch64_be-unknown-linux-gnu_ilp32
            - aarch64_be-unknown-linux-gnu
            - arm64_32-apple-watchos
            - armeb-unknown-linux-gnueabi
            - armv4t-none-eabi
            - armv4t-unknown-linux-gnueabi
            - armv5te-none-eabi
            - armv5te-unknown-linux-uclibceabi
            - armv6-unknown-freebsd
            - armv6-unknown-netbsd-eabihf
            - armv6k-nintendo-3ds
            - armv7-apple-ios
            - armv7-sony-vita-newlibeabihf
            - armv7-unknown-linux-ohos
            - armv7-unknown-linux-uclibceabi
            - armv7-unknown-linux-uclibceabihf
            - armv7-unknown-freebsd
            - armv7-unknown-netbsd-eabihf
            - armv7-wrs-vxworks-eabihf
            - armv7a-kmc-solid_asp3-eabi
            - armv7a-kmc-solid_asp3-eabihf
            - armv7a-none-eabihf
            - armv7k-apple-watchos
            - armv7s-apple-ios
            - avr-unknown-gnu-atmega328
            - bpfeb-unknown-none
            - bpfel-unknown-none
            - hexagon-unknown-linux-musl
            - i386-apple-ios
            - i586-pc-nto-qnx700
            - i686-apple-darwin
            - i686-pc-windows-msvc
            - i686-unknown-haiku
            - i686-unknown-netbsd
            - i686-unknown-openbsd
            - i686-uwp-windows-gnu
            - i686-uwp-windows-msvc
            - i686-wrs-vxworks
            - loongarch64-unknown-linux-gnu
            - m68k-unknown-linux-gnu
            - mips-unknown-linux-uclibc
            - mips64-openwrt-linux-musl
            - mipsel-sony-psp
            - mipsel-sony-psx
            - mipsel-unknown-linux-uclibc
            - mipsel-unknown-none
            - mipsisa32r6-unknown-linux-gnu
            - mipsisa32r6el-unknown-linux-gnu
            - mipsisa64r6-unknown-linux-gnuabi64
            - mipsisa64r6el-unknown-linux-gnuabi64
            - msp430-none-elf
            - powerpc-unknown-linux-gnuspe
            - powerpc-unknown-linux-musl
            - powerpc-unknown-netbsd
            - powerpc-unknown-openbsd
            - powerpc-wrs-vxworks-spe
            - powerpc-wrs-vxworks
            - powerpc64-unknown-freebsd
            - powerpc64le-unknown-freebsd
            - powerpc-unknown-freebsd
            - powerpc64-unknown-linux-musl
            - powerpc64-wrs-vxworks
            - powerpc64le-unknown-linux-musl
            - powerpc64-unknown-openbsd
            - powerpc64-ibm-aix
            - riscv32gc-unknown-linux-gnu
            - riscv32gc-unknown-linux-musl
            - riscv32im-unknown-none-elf
            - riscv32imac-unknown-xous-elf
            - riscv32imc-esp-espidf
            - riscv64gc-unknown-freebsd
            - riscv64gc-unknown-fuchsia
            - riscv64gc-unknown-linux-musl
            - riscv64gc-unknown-openbsd
            - s390x-unknown-linux-musl
            - sparc-unknown-linux-gnu
            - sparc64-unknown-netbsd
            - sparc64-unknown-openbsd
            - thumbv4t-none-eabi
            - thumbv5te-none-eabi
            - thumbv7a-pc-windows-msvc
            - thumbv7a-uwp-windows-msvc
            - thumbv7neon-unknown-linux-musleabihf
            - wasm64-unknown-unknown
            - x86_64-apple-ios-macabi
            - x86_64-apple-tvos
            - x86_64-apple-watchos-sim
            - x86_64-pc-nto-qnx710
            - x86_64-pc-windows-gnullvm
            - x86_64-pc-windows-msvc
            - x86_64-sun-solaris
            # - x86_64-unknown-dragonfly
            - x86_64-unknown-haiku
            - x86_64-unknown-hermit
            - x86_64-unknown-l4re-uclibc
            - x86_64-unknown-openbsd
            - x86_64-uwp-windows-gnu
            - x86_64-uwp-windows-msvc
            - x86_64-wrs-vxworks
            - x86_64h-apple-darwin            
    steps:
      - uses: actions/checkout@v3
      - run: rustc --version || true
        shell: bash
      - uses: dtolnay/rust-toolchain@stable
        if: matrix.target != 'aarch64-unknown-freebsd' || matrix.target != 'armv7-unknown-freebsd' 
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      - name: get musl-tools
        # if: matrix.target == 'x86_64-unknown-linux-musl'
        run: sudo apt install musl-tools
        working-directory: rust/pact_ffi
        shell: bash
      - name: Build pact_ffi with cargo for ${{ matrix.target }}
        run: cargo build --target ${{ matrix.target }} --release
        working-directory: rust/pact_ffi
        shell: bash


  build_cross:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        rust: [ stable ]
        target: # https://github.com/cross-rs/cross/blob/main/targets.toml
            - x86_64-apple-darwin
            - x86_64-unknown-linux-gnu
            - x86_64-unknown-linux-musl
            - x86_64-pc-windows-msvc
            - x86_64-unknown-linux-gnu
            - aarch64-unknown-linux-gnu
            - arm-unknown-linux-gnueabi
            - arm-unknown-linux-gnueabihf
            - armv7-unknown-linux-gnueabi
            - armv7-unknown-linux-gnueabihf
            - thumbv7neon-unknown-linux-gnueabihf
            - i586-unknown-linux-gnu
            - i686-unknown-linux-gnu
            # - mips-unknown-linux-gnu
            # - mipsel-unknown-linux-gnu
            # - mips64-unknown-linux-gnuabi64
            # - mips64el-unknown-linux-gnuabi64
            # - mips64-unknown-linux-muslabi64
            # - mips64el-unknown-linux-muslabi64
            # - powerpc-unknown-linux-gnu
            # - powerpc64-unknown-linux-gnu
            # - powerpc64le-unknown-linux-gnu
            # - riscv64gc-unknown-linux-gnu
            # - s390x-unknown-linux-gnu
            # - sparc64-unknown-linux-gnu
            - aarch64-unknown-linux-musl
            - arm-unknown-linux-musleabihf
            - arm-unknown-linux-musleabi
            - armv5te-unknown-linux-gnueabi
            - armv5te-unknown-linux-musleabi
            - armv7-unknown-linux-musleabi
            - armv7-unknown-linux-musleabihf
            - i586-unknown-linux-musl
            - i686-unknown-linux-musl
            # - mips-unknown-linux-musl
            # - mipsel-unknown-linux-musl
            - aarch64-linux-android
            - arm-linux-androideabi
            - armv7-linux-androideabi
            - thumbv7neon-linux-androideabi
            - i686-linux-android
            - x86_64-linux-android
            - x86_64-pc-windows-gnu
            - i686-pc-windows-gnu
            - asmjs-unknown-emscripten
            # - wasm32-unknown-emscripten
            - x86_64-unknown-dragonfly
            # - i686-unknown-freebsd
            - x86_64-unknown-freebsd
            - x86_64-unknown-netbsd
            # - sparcv9-sun-solaris
            - x86_64-sun-solaris
            - x86_64-unknown-illumos
            # - thumbv6m-none-eabi
            # - thumbv7em-none-eabi
            # - thumbv7em-none-eabihf
            # - thumbv7m-none-eabi
            - thumbv8m.base-none-eabi
            - thumbv8m.main-none-eabi
            - thumbv8m.main-none-eabihf
            - aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - run: rustc --version || true
        shell: bash
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: install cross for ${{ matrix.target }}
        run: cargo install cross
        working-directory: rust/pact_ffi
        shell: bash
      - name: Build pact_ffi with cross for ${{ matrix.target }}
        run: cross build --target ${{ matrix.target }} --release
        working-directory: rust/pact_ffi
        shell: bash

  build_mac:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ macos-latest ]
        rust: [ stable ]
        target: 
          - aarch64-apple-darwin
          - x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v3
      - run: rustc --version || true
        shell: bash
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      - name: Build pact_ffi
        run: cargo build --target ${{ matrix.target }} --release
        working-directory: rust/pact_ffi
        shell: bash

  build_windows:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ windows-latest ]
        rust: [ stable ]
        target: 
          - x86_64-pc-windows-msvc
          - aarch64-pc-windows-msvc
          - i686-pc-windows-msvc
    steps:
      - uses: actions/checkout@v3
      - run: rustc --version || true
        shell: bash
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      - name: Build pact_ffi
        if: matrix.target == 'aarch64-pc-windows-msvc'
        run: |
            echo ring = { git = \"https://github.com/awakecoding/ring\", branch = \"0.16.20_alpha\" } >> cargo.toml
            cargo update 
        working-directory: rust
        shell: bash
      - name: Build pact_ffi
        run: cargo build --target ${{ matrix.target }} --release
        working-directory: rust/pact_ffi
        shell: bash